# Exploratory Data Analysis (EDA) – Notebook 1  
## Data Understanding and Data Quality Assessment

### Objective:
The goal of this notebook is to perform an initial exploratory analysis of the dataset in order to:
- Understand the structure and content of the data
- Identify data quality issues (missing values, duplicates, invalid values)
- Perform basic statistical analysis
- Prepare the dataset for deeper exploratory analysis and modeling

This notebook focuses on **what the data is and how clean it is**, without drawing analytical insights yet.

In [3]:
import pandas as pd
import numpy as np

In [5]:
%pip install pymongo

Collecting pymongo
  Downloading pymongo-4.15.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.15.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 19.1 MB/s eta 0:00:00a 0:00:01
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 30.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.15.5

In [6]:
from pymongo import MongoClient
import pandas as pd

# =================================================================
# 🛠️ CLOUD CONFIGURATION
# =================================================================
ATLAS_URI = "mongodb+srv://omarkhattab220_db_user:eoQTMUOc4nx1GhdB@cluster0.m5r7r3o.mongodb.net/?appName=Cluster0"
# =================================================================

def get_mongo_data(uri=ATLAS_URI):
    """
    Connects to MongoDB Atlas and returns the cleaned transactions as a DataFrame.
    """
    try:
        # 1. Establish Cloud Connection
        # We use a 5-second timeout so it doesn't hang if your internet is slow
        client = MongoClient(uri, serverSelectionTimeoutMS=5000)
        
        # 2. Verify connection
        client.admin.command('ping')
        print("✅ Connected to MongoDB Atlas successfully!")

        # 3. Access your specific database and collection
        db = client["fraud_db"]
        collection = db["transactions"]
        
        # 4. Fetch all records
        cursor = collection.find({})
        df = pd.DataFrame(list(cursor))

        if df.empty:
            print("⚠️ The database is connected, but the collection is empty.")
            return None
            
        # 5. Drop the MongoDB internal ID for a cleaner ML DataFrame
        if '_id' in df.columns:
            df = df.drop(columns=['_id'])

        return df

    except Exception as e:
        print(f"❌ Connection Failed: {e}")
        print("\n💡 Check: Did you 'Allow Access from Anywhere' in Atlas Network Access?")
        return None

if __name__ == "__main__":
    # This block allows your teammates to run the script directly from a terminal
    print("☁️ Fetching data from the cloud...")
    data = get_mongo_data()
    
    if data is not None:
        filename = "fraud_data_cloud.csv"
        data.to_csv(filename, index=False)
        print(f"✅ Success! {len(data)} records saved to {filename}")

☁️ Fetching data from the cloud...
✅ Connected to MongoDB Atlas successfully!
✅ Success! 284807 records saved to fraud_data_cloud.csv

## Dataset Loading

We begin by loading the credit card transactions dataset.  
This dataset contains anonymized transaction features and is commonly used for fraud detection tasks.

In [7]:
df = pd.read_csv("fraud_data_cloud.csv")

## Preview of the Dataset

We display the first few rows to understand:
- The general structure
- Column naming
- The type of values stored in each column

In [8]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,282.0,-0.356466,0.725418,1.971749,0.831343,0.369681,-0.107776,0.751610,-0.120166,-0.420675,...,0.020804,0.424312,-0.015989,0.466754,-0.809962,0.657334,-0.043150,-0.046401,0.0,0
1,380.0,-1.299837,0.881817,1.452842,-1.293698,-0.025105,-1.170103,0.861610,-0.193934,0.592001,...,-0.272563,-0.360853,0.223911,0.598930,-0.397705,0.637141,0.234872,0.021379,0.0,0
2,403.0,1.237413,0.512365,0.687746,1.693872,-0.236323,-0.650232,0.118066,-0.230545,-0.808523,...,-0.077543,-0.178220,0.038722,0.471218,0.289249,0.871803,-0.066884,0.012986,0.0,0
3,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.0,1
4,430.0,-1.860258,-0.629859,0.966570,0.844632,0.759983,-1.481173,-0.509681,0.540722,-0.733623,...,0.268028,0.125515,-0.225029,0.586664,-0.031598,0.570168,-0.043007,-0.223739,0.0,0

## Dataset Dimensions

We check the number of rows and columns to understand the scale of the data.
This is especially important in a Big Data context.

In [9]:
df.shape

(284807, 31)

## Column Description

- `Time`: Seconds elapsed between each transaction and the first transaction
- `V1` to `V28`: Anonymized features obtained using PCA transformation
- `Amount`: Transaction amount
- `Class`: Target variable  
  - `0` → Normal transaction  
  - `1` → Fraudulent transaction

In [10]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

## Data Types and Structure

We inspect data types to:
- Verify that numerical features are correctly stored
- Detect potential data type issues

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

## Missing Values Analysis

Missing values can negatively impact model performance.
We check whether any columns contain missing data.

In [12]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

## Percentage of Missing Values

We calculate the percentage of missing values per column to confirm data completeness.

In [13]:
(df.isnull().sum() / len(df)) * 100

Time      0.0
V1        0.0
V2        0.0
V3        0.0
V4        0.0
V5        0.0
V6        0.0
V7        0.0
V8        0.0
V9        0.0
V10       0.0
V11       0.0
V12       0.0
V13       0.0
V14       0.0
V15       0.0
V16       0.0
V17       0.0
V18       0.0
V19       0.0
V20       0.0
V21       0.0
V22       0.0
V23       0.0
V24       0.0
V25       0.0
V26       0.0
V27       0.0
V28       0.0
Amount    0.0
Class     0.0
dtype: float64

## Duplicate Records Check

Duplicate transactions can bias the model.
We check for duplicated rows in the dataset.

In [14]:
df.duplicated().sum()

np.int64(1081)

## Statistical Summary of Numerical Features

We compute basic descriptive statistics to understand:
- Central tendency
- Spread
- Presence of extreme values

In [15]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.187934e-15,3.704312e-16,-1.392310e-15,2.094852e-15,1.002719e-15,1.497691e-15,-5.364865e-16,1.133647e-16,-2.400617e-15,...,1.532819e-16,-3.456825e-16,2.610582e-16,4.472417e-15,5.141329e-16,1.681260e-15,-3.717285e-16,-1.225457e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

## Target Variable Distribution

We analyze the distribution of the target variable (`Class`) to check for class imbalance.

In [16]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

### Observation:
The dataset is **highly imbalanced**, with fraudulent transactions representing a very small fraction of the data.

This observation is critical and will strongly influence:
- Model selection
- Evaluation metrics
- Sampling techniques

## Saving the Clean Dataset

Since the dataset shows no missing or duplicate values, we save it for use in further analysis and modeling.

In [17]:
df.to_csv("cleaned_creditcard_data.csv", index=False)

## Notebook 1 Conclusion

In this notebook, we:
- Explored the dataset structure and features
- Verified data quality (no missing or duplicate values)
- Identified severe class imbalance
- Generated a clean dataset for further analysis

The next notebook will focus on **visualizations, correlations, and analytical insights**.